export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const SET_LOGIN_ALERT = 'SET_LOGIN_ALERT';
export const CLEAR_LOGIN_ALERT = 'CLEAR_LOGIN_ALERT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const CLEAR_REGISTER_ALERT = 'CLEAR_REGISTER_ALERT';

export const SET_INITIAL_TOKENS = 'SET_INITIAL_TOKENS';
export const SET_NEW_TOKENS = 'SET_NEW_TOKENS';
export const REMOVE_TOKENS = 'REMOVE_TOKENS';
export const SET_REFRESH_TOKENS_PROMISE = 'SET_REFRESH_TOKEN_PROMISE';
export const CLEAR_REFRESH_TOKENS_PROMISE = 'CLEAR_REFRESH_TOKEN_PROMISE';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const JOIN_CONVERSATION = 'JOIN_CONVERSATION';
export const LEAVE_CONVERSATION = 'LEAVE_CONVERSATION';

export const GET_CONVERSATIONS_REQUEST = 'GET_CONVERSATIONS_REQUEST';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAILURE = 'GET_CONVERSATIONS_FAILURE';
export const SET_USERS_ONLINE = 'SET_USERS_ONLINE';
export const SET_USERS_OFFLINE = 'SET_USERS_OFFLINE';

export const ADD_NEW_CONVERSATION_SUCCESS = 'ADD_NEW_CONVERSATION_SUCCESS';
export const ADD_NEW_CONVERSATION_FAILURE = 'ADD_NEW_CONVERSATION_FAILURE';
export const REMOVE_CONVERSATION_SUCCESS = 'REMOVE_CONVERSATION_SUCCESS';
export const REMOVE_CONVERSATION_FAILURE = 'REMOVE_CONVERSATION_FAILURE';
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';
export const REMOVE_CONVERSATIONS_FROM_STORE = 'REMOVE_CONVERSATIONS_FROM_STORE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const ON_SOCKET_CONNECTION = 'ON_SOCKET_CONNECTION';
export const ON_RECEIVED_MESSAGE = 'ON_RECEIVED_MESSAGE';
export const REMOVE_SOCKET_CONNECTION = 'REMOVE_SOCKET_CONNECTION';
export const GET_MESSAGES_REQUEST = 'GET_MESSAGES_REQUEST';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';
