export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const SET_LOGIN_ALERT = 'SET_LOGIN_ALERT';
export const CLEAR_LOGIN_ALERT = 'CLEAR_LOGIN_ALERT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const CLEAR_REGISTER_ALERT = 'CLEAR_REGISTER_ALERT';

export const SET_INITIAL_TOKENS = 'SET_INITIAL_TOKENS';
export const SET_NEW_TOKENS = 'SET_NEW_TOKENS';
export const REMOVE_TOKENS = 'REMOVE_TOKENS';
export const SET_REFRESH_TOKENS_PROMISE = 'SET_REFRESH_TOKEN_PROMISE';
export const CLEAR_REFRESH_TOKENS_PROMISE = 'CLEAR_REFRESH_TOKEN_PROMISE';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const ROUTE_CHANGE = 'ROUTE_CHANGE';
